# PyTorch Tensors

In [2]:
import torch

### Construct a vector w/ 3 entries and a 2 x 2 matrix

In [5]:
x = torch.Tensor([5.2, 7.4, -3.7])
print (x)

A = torch.Tensor([[1, 2], [3, 4]])
print (A)

tensor([ 5.2000,  7.4000, -3.7000])
tensor([[1., 2.],
        [3., 4.]])


### Construct a random 10 x 2 matrix, a all-zero 10 x 2 matrx, and a 5 x 2 x 2 random tensor

In [13]:
A = torch.rand(10, 2)
print (A)
A = torch.zeros(10, 2)
print (A)
B = torch.rand(5, 3, 2)
print (B)

tensor([[0.9830, 0.4678],
        [0.3419, 0.3918],
        [0.5759, 0.6720],
        [0.2561, 0.3461],
        [0.3877, 0.7986],
        [0.5487, 0.4546],
        [0.0845, 0.1431],
        [0.4031, 0.9482],
        [0.1408, 0.1263],
        [0.8252, 0.1803]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[[0.0983, 0.1155],
         [0.4341, 0.0534],
         [0.9220, 0.5694]],

        [[0.2349, 0.6855],
         [0.1230, 0.8714],
         [0.4032, 0.1466]],

        [[0.0153, 0.0198],
         [0.2251, 0.3310],
         [0.0970, 0.3222]],

        [[0.8654, 0.4677],
         [0.2503, 0.7893],
         [0.6792, 0.8088]],

        [[0.2485, 0.8528],
         [0.4216, 0.5319],
         [0.3497, 0.4622]]])


### Size and Dimension of a Tensor

In [14]:
print (B.dim())
print (B.size())
print (B.size(0))
print (B.size(1))
print (B.size(2))

3
torch.Size([5, 3, 2])
5
3
2


### Adding and Multiplying Tensors

In [15]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)

C = 2 * B
D = A + C
E = A * B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(D)
print('')
print(E)

tensor([[0.2463, 0.8266],
        [0.1004, 0.0629]])

tensor([[0.5185, 0.9016],
        [0.6821, 0.9384]])

tensor([[1.0370, 1.8031],
        [1.3643, 1.8769]])

tensor([[1.2834, 2.6297],
        [1.4647, 1.9398]])

tensor([[0.1277, 0.7453],
        [0.0685, 0.0591]])


### Float / Integer Conversions

In [17]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [18]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [19]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [20]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other Constructors

In [21]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [22]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([7, 1, 2, 0, 8, 3, 9, 4, 5, 6])
torch.LongTensor
