# Slicing and Reshaping

In [2]:
import torch

### Reshaping a Tensor

In [3]:
x = torch.arange(10)
print (x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [4]:
print (x.view(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [5]:
print (x.view(5, 2))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [6]:
# to make a change permanent, you need to create a new tensor
y = x.view(5, 2)
print (x)
print (y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [7]:
print (y[0])  # extract row 0
print (y[1])  # extract row 1
v = y[2]
print (v)

tensor([0, 1])
tensor([2, 3])
tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [9]:
print (y[1:4])

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Accessing the entries of a tensor

In [11]:
print (y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [12]:
a = y[4, 0] # extract entry (4, 0) of the matrix
print (a)

tensor(8)


### A matrix is a 2-dimensional tensor, a row of a matrix is 1-dimensional tensor, an entry of a matrix is a 0-dimensional tensor; 0-dimensional tensor is scalar. If we want to convert a 0-dimensional tensor into python number, we need to use item()

In [14]:
b = a.item()
print (a)
print (b)

tensor(8)
8
