# PyTorch Module

In [2]:
import torch
import torch.nn as nn

### Make a Linear Module that takes input of size 5 and return output of size 3

In [4]:
mod = nn.Linear(5, 3, bias = True)
print (mod)

Linear(in_features=5, out_features=3, bias=True)


### Make a random tensor of size 5 and feed it to the module

In [6]:
x = torch.rand(5)
print (x)

tensor([0.6526, 0.9009, 0.8940, 0.4229, 0.8283])


In [7]:
y = mod(x)
print (y)

tensor([-0.7936, -0.2648, -0.1926], grad_fn=<ThAddBackward>)


In [10]:
print (mod.weight)

Parameter containing:
tensor([[-0.2912, -0.4156, -0.1520,  0.3542,  0.0625],
        [ 0.1347,  0.1585,  0.1163,  0.1289, -0.4435],
        [ 0.3863, -0.3365, -0.1736,  0.1802, -0.0861]], requires_grad=True)


In [11]:
print (mod.bias)

Parameter containing:
tensor([-0.2948, -0.2867,  0.0087], requires_grad=True)


### If we want to change the internal parameters of the module

In [12]:
mod.weight[0, 0] = 0
mod.weight[0, 1] = 1
mod.weight[0, 2] = 2
print (mod.weight)

Parameter containing:
tensor([[ 0.0000,  1.0000,  2.0000,  0.3542,  0.0625],
        [ 0.1347,  0.1585,  0.1163,  0.1289, -0.4435],
        [ 0.3863, -0.3365, -0.1736,  0.1802, -0.0861]], grad_fn=<CopySlices>)


### A Linear Module without bias

In [14]:
mod2 = nn.Linear(5, 3, bias = False)
print (mod2)
print (mod2.weight)
print (mod2.bias)

Linear(in_features=5, out_features=3, bias=False)
Parameter containing:
tensor([[ 0.0272, -0.4360, -0.1218,  0.1081, -0.1776],
        [ 0.1720, -0.1708, -0.0866,  0.1352, -0.1931],
        [ 0.0923, -0.1571, -0.0887, -0.1592,  0.3676]], requires_grad=True)
None
