In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### In PyTorch, networks are always defined via classes

In [2]:
class two_layer_net(nn.Module):

    def __init__(self, input_size, hidden_size, output_size):
        super(two_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, hidden_size , bias=True)
        self.layer2 = nn.Linear( hidden_size, output_size , bias=True)        
        
    def forward(self, x):
        
        x = self.layer1(x)
        x = F.relu(x)
        x = self.layer2(x)
        p = F.softmax(x, dim=0)
        
        return p

### Create an instance with: 
* Input Size = 2
* Hidden Size = 5
* Output Size = 3

In [20]:
net = two_layer_net(2, 5, 3)
print (net)

two_layer_net(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


### All parameters of a network can be accessed by net.parameters()

In [21]:
list_of_param = list(net.parameters())
print (list_of_param)

[Parameter containing:
tensor([[-0.3272, -0.2431],
        [-0.1594, -0.0526],
        [-0.2624, -0.5536],
        [ 0.2884,  0.6905],
        [ 0.3324,  0.2276]], requires_grad=True), Parameter containing:
tensor([ 0.6588, -0.4061,  0.5958, -0.3426,  0.0707], requires_grad=True), Parameter containing:
tensor([[-0.0167, -0.1247, -0.3945,  0.1250, -0.2837],
        [ 0.4059,  0.3622, -0.0934, -0.2736,  0.4210],
        [-0.4255,  0.2218, -0.1033, -0.0213,  0.2958]], requires_grad=True), Parameter containing:
tensor([-0.2718,  0.1303,  0.1983], requires_grad=True)]


### We can access the first module as follow:

In [22]:
print (net.layer1)
print (net.layer1.weight)
print (net.layer1.bias)

Linear(in_features=2, out_features=5, bias=True)
Parameter containing:
tensor([[-0.3272, -0.2431],
        [-0.1594, -0.0526],
        [-0.2624, -0.5536],
        [ 0.2884,  0.6905],
        [ 0.3324,  0.2276]], requires_grad=True)
Parameter containing:
tensor([ 0.6588, -0.4061,  0.5958, -0.3426,  0.0707], requires_grad=True)


### Change the weights from layer 1

In [23]:
net.layer1.weight[0, 0] = 1
net.layer1.weight[0, 1] = 2
print (net.layer1.weight)

Parameter containing:
tensor([[ 1.0000,  2.0000],
        [-0.1594, -0.0526],
        [-0.2624, -0.5536],
        [ 0.2884,  0.6905],
        [ 0.3324,  0.2276]], grad_fn=<CopySlices>)


### Make an input vector and feed it into the network

In [24]:
x = torch.Tensor([1, 1])
print (x)

tensor([1., 1.])


In [25]:
p = net.forward(x)
print (p)

tensor([0.1004, 0.8524, 0.0473], grad_fn=<SoftmaxBackward>)


### Forward method can be written as follows

In [26]:
p = net(x)
print (p)

tensor([0.1004, 0.8524, 0.0473], grad_fn=<SoftmaxBackward>)


### Check the probability vector indeed sum to 1

In [27]:
print (p.sum())

tensor(1.0000, grad_fn=<SumBackward0>)
